### ISSUE TITLE
Unable to download weights

### ISSUE THREAD

**Issue by Daniel-1597** [xuannianz/keras-GaussianYOLOv3#1]

**Comment by xuannianz** [comment]
Hi @Daniel-1597, I have uploaded the weights files to google driver. https://drive.google.com/open?id=1PwmVx1jct9ee2o2_m_lXObkyN3fSHo08

**Comment by Daniel-1597** [comment]
yeah sure thanks

**Comment by Daniel-1597** [comment]
Sir, Can you write a code that works for a video as well?

**Comment by xuannianz** [comment]
I will do that later. For now, you can refer to https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo.py#L172-L211 .

**Comment by Daniel-1597** [comment]
Sure sir

**Comment by Daniel-1597** [comment]
Done with video capture it's giving around 3 Fps on 1050ti i7 8th gen

**Comment by Daniel-1597** [comment]
How can we optimize this sir

**Comment by xuannianz** [comment]
I have no idea, have you compared with the official implementation?

**Comment by Daniel-1597** [comment]
The official implementation is in darknet I haven't implemented the darknet code but I tried to convert it to keras but I got errors
