### ISSUE TITLE
Can we try Gaussian Method on yolo_v2

### ISSUE THREAD

**Issue by Daniel-1597** [xuannianz/keras-GaussianYOLOv3#3]

**Comment by Daniel-1597** [comment]
Can you explain to me the lines below what is the use of these lines?

    fm_13_input = Input(shape=(None, None, num_anchors_per_layer, num_classes + 5), name='fm_13_input')

    fm_26_input = Input(shape=(None, None, num_anchors_per_layer, num_classes + 5), name='fm_26_input')
    fm_52_input = Input(shape=(None, None, num_anchors_per_layer, num_classes + 5), name='fm_52_input')

**Comment by xuannianz** [comment]
1. I think we can. They use the same logic to predict bounding boxes.
2. There three inputs would be assigned to ground truth of the feature maps so that we can compute the loss conveniently.

**Comment by Daniel-1597** [comment]
[1905.01296v2.pdf](https://github.com/xuannianz/keras-GaussianYOLOv3/files/3882793/1905.01296v2.pdf)
If possible can you implement this paper

**Comment by xuannianz** [comment]
Aha, it's indeed beyond my knowledge.

**Comment by Daniel-1597** [comment]
That's the toughest I gave ever read
